# Generated by Django 5.2.5 on 2025-08-21 20:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0001_initial'),
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='room',
            name='ingress_id',
        ),
        migrations.RemoveField(
            model_name='room',
            name='movie_url',
        ),
        migrations.AddField(
            model_name='room',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='max_participants',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='invite_duration_minutes',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='room',
            name='meet_datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='movie.movie'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
