# Generated by Django 5.2.5 on 2025-08-22 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moviereview',
            options={'ordering': ['-id']},
        ),
    ]
