# Generated by Django 5.2.5 on 2025-08-13 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='conversion_status',
        ),
        migrations.RemoveField(
            model_name='room',
            name='hls_path',
        ),
        migrations.RemoveField(
            model_name='room',
            name='movie_file',
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('movie_file', models.FileField(upload_to='movies/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='movie_thumbnails/')),
                ('duration_minutes', models.IntegerField(help_text='Movie duration in minutes')),
                ('genre', models.CharField(blank=True, max_length=100)),
                ('release_year', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this movie is available for selection')),
                ('hls_path', models.CharField(blank=True, max_length=500, null=True)),
                ('conversion_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('uploaded_by', models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='room',
            name='selected_movie',
            field=models.ForeignKey(default=2, help_text='Movie selected from admin-uploaded collection', on_delete=django.db.models.deletion.CASCADE, to='meet.movie'),
            preserve_default=False,
        ),
    ]
