# Generated by Django 5.2.5 on 2025-08-13 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0002_add_movie_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='selected_movie',
            field=models.ForeignKey(blank=True, help_text='Movie selected from admin-uploaded collection', null=True, on_delete=django.db.models.deletion.CASCADE, to='meet.movie'),
        ),
    ]
