# Generated by Django 5.2.5 on 2025-08-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0003_fix_selected_movie_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
