# Generated by Django 5.2.5 on 2025-08-20 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0004_alter_movie_is_active'),
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='selected_movie',
            field=models.ForeignKey(blank=True, help_text='Movie selected from admin-uploaded collection', null=True, on_delete=django.db.models.deletion.CASCADE, to='movie.movie'),
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
